### ISSUE TITLE
AOKP inspiration

### ISSUE THREAD

**Issue by iamtheblackunicorn** [iamtheblackunicorn/iamtheblackunicorn.github.io#1]
Hey @scar45 what do you think of this theme?

**Comment by scar45** [comment]
Looks nice, great job!

**Comment by iamtheblackunicorn** [comment]
Thank you very much for saying that @scar45 ! Is there anything that can be improved or made prettier/better? Also, I could help with the AOKP online-presence, if you wanted? 🙈

**Comment by iamtheblackunicorn** [comment]
Nothing more to be said, I take it.

**Comment by scar45** [comment]
The only thing I would change is the `font-weight` of your paragraphs, as I find the text is a bit tough to read. I would add `font-weight: bold` to `blackunicorn.css` on Line 75. That increases the font 'thickness' and it appears to be easier to read.

I must tell you that I have not been involved with the AOKP project for more than 2 years. Life has taken me in a different/busy direction since, and while my work on AOKP.co remains, it is only a legacy. I can't even tell you where to get in touch with AOKP, but the XDA forums might be a starting point. It's always good to offer your contributions to such open-source projects (once you can find the main point of contact). All the best.

**Comment by iamtheblackunicorn** [comment]
You're right, I did change it actually and it immediately looked much better. Really? May I ask where?🙈 And I actually just wanted to mimick the design and tjhe color-scheme because I thought it looked very good! Also, is there somehwere that we can chat privately? I have a suggestion I would like to make to you! 🤔🙈

**Comment by scar45** [comment]
Glad to know that you liked + implemented my suggestion!

As for your own suggestion to me, what is it in regards to?

**Comment by iamtheblackunicorn** [comment]
That was that small little bit missing to make it just that little bit more alluring.

I wanted to ask whether you would be interested in joining a "coder" collective I am looking to start. Because I was thinking if one is in a group of other coders, one could learn from the other member's prior experience, help each other with problems, get feedback and most importantly of all, collaborate on a focussed project, combining the expertise of each coder in one maybe "break-through" project. (Doesn't have to be break-through). Because I find myself quite alone here in regard to coding and collaborating with other people and hetting feedback here in Vienna, Austria. Would you be interested in that? Also, we could have a fun mood, maybe meet once in a while for coding sessions. I was thinking we could convene in a Discord channel, maybe?

**Comment by iamtheblackunicorn** [comment]
Specifically this is how I imagined it: There would be six of us, each of us would be a specific color "unicorn" (following the AOKP way) and each of us would have one area of expertise to mark us apart from the others.

**Comment by scar45** [comment]
I think your idea is great, and certainly worth pursuing, however I am afraid I don't have the capacity myself.

I am thankful for your suggestion, and understand your position, but it's just not in the cards for me unfortunately. Don't let that stop you though!

**Comment by iamtheblackunicorn** [comment]
Hey! Sorry that I didn't reply to your comment, I was very busy with uni and some projects I was working on for myself. I hope you're doing alright. If you would like to join at any time, just let me know! I'd be more than happy to have you on the "team". I wrote to a couple of people, but most of them declined due to either being too caught up with other stuff or by not wanting to collaborate with a "rookie" like me, as they put that but I guess that is their opinion, doesn't really bother me. I have to thank you for giving me the feedback you did and I completely understand your point of view. 🙈
